name: RSS to Discord

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

# evita dois processos ao mesmo tempo (ESSENCIAL)
concurrency:
  group: rss-bot
  cancel-in-progress: true

# permite push no repo
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - run: npm install

      - run: node rss.js
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RSS_URLS: ${{ secrets.RSS_URLS }}

      - name: Save state
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"

          git pull --rebase || true
          git add sent.json || true
          git commit -m "update sent" || true
          git push || true
